### ISSUE TITLE
weblate - cannot register/contact admins; slack l10n group expired invitation

### ISSUE THREAD

**Issue by p-bo** [elementary/website#2351]
Hello,

tried to register on your weblate instance, but no e-mails arrived (two attempts, few hours between therm, spam/all mails checked). Then tried contact trough form in weblate, but sending it stated only internal server error.
Then tried to join to l10n slack group trough invitation link on website section for translators only to see, that this invitation is expired.

May I ask you to check it please?

Thanks and have a nice day :)
Pavel

**Comment by lewisgoddard** [comment]
Duplicate of #2255

**Comment by p-bo** [comment]
And what about weblate registration / contact part - fixed already?

**Comment by danrabbit** [comment]
@p-bo I believe weblate should be fixed now. I think @tintou addressed that the other day

**Comment by p-bo** [comment]
@tintou I'm afraid, that problem persists - tried again, no mail arrived, and sending form for reporting problem with registration is still generating only Internal error - may I ask you to check please?
Thanks

**Comment by p-bo** [comment]
May I politely remind you this problem please?
Tried today (this from different browser) and problem with registration (form send, but no mail arrived) and registration issue problem form (cannot send, internal server error) persists.

**Comment by tintou** [comment]
@p-bo Hi there! I'm fully aware of the issue, we'll get someone to fix this soonish :)

**Comment by p-bo** [comment]
Hello,

well, as a workaround I used my Github account (this one).
Because still not possible to join Slack translators group (see #2255), may I ask for granting right to save (not only suggest) translations please?

Thanks

**Comment by p-bo** [comment]
@tintou May I ask you to grant p-bo rights to save translations? Now I'm doing suggestions, but there are suggestions from others years old - I'm worried, that new suggestions will be wasted too...

**Comment by tintou** [comment]
@p-bo That's a thing I'm indeed able to do, done :slightly_smiling_face:

**Comment by p-bo** [comment]
@tintou Great! thanks :)
